### ISSUE TITLE
How to use manual message acknowledgement?

### ISSUE THREAD

**Issue by ragibkl** [lukadriel7/nestjs-rabbitmq-transporter#1]
Hi, I've been using this lib, and quite impressed with it.

I do have a question. Is there a way to make [manual message acknowledgement](https://docs.nestjs.com/microservices/rabbitmq#message-acknowledgement) to work?

I tried the following:
```
// main.ts
const app = await NestFactory.create(AppModule);
  app.connectMicroservice<MicroserviceOptions>({
    strategy: new RabbitMQServer({
      queue: 'api-webhooks',
      exchange: 'events_topic',
      exchangeType: ExchangeType.TOPIC,
      urls: ['amqp://guest:guest@rabbitmq:5672'],  
      noAck: false,
    }),
  });

// controller
@Controller()
export class EventsController {
  constructor(private readonly eventsService: EventsService) {}

  @EventPattern('shipment_created')
  create(@Payload() shipmentCreatedDto: any, @Ctx() context: RmqContext) {
    const channel = context.getChannelRef();
    const originalMsg = context.getMessage();

    try {
      this.eventsService.create(shipmentCreatedDto);
      channel.ack(originalMsg);
    } catch (error) {
      console.log(error)
      channel.nack(originalMsg);
    }
  }
}
```

Error logs:
```
api-sms_1        | [Nest] 213  - 01/04/2022, 8:07:19 AM   ERROR [Server] Disconnected from RMQ. Trying to reconnect.
api-sms_1        | [Nest] 213  - 01/04/2022, 8:07:19 AM   ERROR [Server] Object:
api-sms_1        | {
api-sms_1        |   "err": {
api-sms_1        |     "code": 406,
api-sms_1        |     "classId": 60,
api-sms_1        |     "methodId": 80
api-sms_1        |   }
api-sms_1        | }

rabbitmq_1       | 2022-01-04 08:07:19.865636+00:00 [erro] <0.1732.0> Channel error on connection <0.1723.0> (172.18.0.5:43108 -> 172.18.0.3:5672, vhost: '/', user: 'guest'), channel 1:
rabbitmq_1       | 2022-01-04 08:07:19.865636+00:00 [erro] <0.1732.0> operation basic.ack caused a channel exception precondition_failed: unknown delivery tag 1
rabbitmq_1       | 2022-01-04 08:07:19.871821+00:00 [warn] <0.1723.0> closing AMQP connection <0.1723.0> (172.18.0.5:43108 -> 172.18.0.3:5672, vhost: '/', user: 'guest'):
rabbitmq_1       | 2022-01-04 08:07:19.871821+00:00 [warn] <0.1723.0> client unexpectedly closed TCP connection
```

**Comment by ragibkl** [comment]
Hi @lukadriel7 ,

I saw this line:
https://github.com/lukadriel7/nestjs-rabbitmq-transporter/blob/e1136d398a8cf0424ad58f7d08a5d0fba2c1b21f/src/server/rabbitmq.server.ts#L77-L79

I think, even if user pass in `{ noAck: false }`, it would still interpret as `{ noAck: true }`.

Maybe it's a simple fix as follows:
```
channel.consume(queue, (msg) => this.handleMessage(msg, channel), { 
    // noAck: noAck ? noAck : true, 

    noAck, // pass directly
    noAck: noAck === false ? false : true, // check if false
    noAck: noAck !== undefined ? noAck : true // check if undefined
});
```

Let me know if I should help with anything.

EDIT: updated suggested code change.

**Comment by lukadriel7** [comment]
Hey, yes you are right thank you for that. I will make the change as soon as possible. At the latest, tomorrow.

**Comment by lukadriel7** [comment]
@ragibkl Hey, I published a new version with the changes, thank you very much for spotting that.

**Comment by lukadriel7** [comment]
Just asking, have you tried using it with any other exchanges ?

**Comment by ragibkl** [comment]
Hi @lukadriel7, Thanks for the quick fix! Much appreciated! I'll test them out.

**Comment by ragibkl** [comment]
Hi @lukadriel7 ,

I'm only using `ExchangeType.TOPIC` now, but another teammate is also using `ExchangeType.FANOUT`.

The fanout is working as expected, but we have issue with lots of queues building up in rabbitmq.

Each time we deploy, start the nestjs process, a queue with random name is created. But when the process is taken down, the queue is not being deleted or cleaned up. So each deployment, more queues are created. We are cleaning up this manually for now.

I'm not too familiar with this subject, but maybe we need to use queue option `{ exclusive: true }` to make it work well? TBH I haven't looked at it much.

**Comment by ragibkl** [comment]
Hi @lukadriel7 , 
We tested the update today, and it seems that the `/dist` folder is empty? Maybe you forgot to run the build step before you publish? Could you check on this?

**Comment by lukadriel7** [comment]
@ragibkl yes sorry about that, I just built and published it. I need to automate it to not forget in the future. I will get to it as soon as I have time

**Comment by ragibkl** [comment]
Hi @lukadriel7 , don't worry about it, it happens to even the best among us! Thanks for the quick action!

We haven't tested it out yet. We will test it, and report back in a day or two if the fix solved our problem.

**Comment by ragibkl** [comment]
Hi @lukadriel7 ,

We tested this, and it works well for us now using `{ noAck: false }` and manual message acknowledgement. Thanks for the fix!
I'll close this issue now. Thanks for all the help! Much appreaciated!
